apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eatbreakfast-club
  region: us-east-2

nodeGroups:
  - name: eatbreakfast-club-nodes
    instanceType: t3.micro
    desiredCapacity: 1

fargateProfiles:
  - name: fp-default
    selectors:
      # All workloads in the "default" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: default
      # All workloads in the "kube-system" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: kube-system
  - name: fp-dev
    selectors:
      # All workloads in the "dev" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:
      - namespace: dev
        labels:
          env: dev
          checks: passed
