apiVersion: apps/v1
kind: Deployment
metadata:
  name: eatbreakfast-club-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      initContainers:
        - name: storage-volumn-permission-fix
          image: busybox
          command: ["/bin/chmod","-R","777", "/rails/storage"]
          volumeMounts:
            - mountPath: /rails/storage
              name: storage-volume
      containers:
        - name: app
          image: ghcr.io/defeated/eatbreakfast.club:main
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /rails/storage
              name: storage-volume
          ports:
            - containerPort: 8080
          env:
            - name: CDN_HOST
              value: cdn.eatbreakfast.club
            - name: THRUSTER_HTTP_PORT
              value: "8080"
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: rails-secrets
                  key: rails_master_key
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: rails-storage-pvc
