apiVersion: v1
kind: Service
metadata:
  name: eatbreakfast-club-load-balancer
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-default-protocol: "http"
    service.beta.kubernetes.io/linode-loadbalancer-port-80: '{"protocol": "http"}'
    service.beta.kubernetes.io/linode-loadbalancer-check-type: "http"
    service.beta.kubernetes.io/linode-loadbalancer-check-path: "/up"
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
    - name: http
      port: 80
      targetPort: 8080
