apiVersion: v1
kind: Service
metadata:
  name: eatbreakfast-club-load-balancer
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-http-ports: "80"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/up"
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
    - name: http
      port: 80
      targetPort: 8080
