apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rails-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: linode-block-storage-retain
