name: Deploy

on:
  workflow_run:
    workflows: [Publish]
    types: [completed]
    branches: [main]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}:main
  K8S_DEPLOY: deployment/eatbreakfast-club-deployment
  KUBECONFIG: ./lke-kubeconfig

jobs:
  deploy-k8s:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - uses: linode/action-linode-cli@v1
        with:
          token: ${{ secrets.LKE_GH_K8S_CFG_TOKEN }}
      - run: linode-cli lke kubeconfig-view ${{ vars.LKE_K8S_CLUSTER }} --text --no-headers | base64 -d > $KUBECONFIG
      - run: kubectl rollout restart $K8S_DEPLOY
      - run: kubectl rollout status $K8S_DEPLOY
